[
    { "name": "Guitarrista" },
    { "name": "Pianista" },
    { "name": "Baterista" },
    { "name": "Violinista" },
    { "name": "Profesor de Inglés" },
    { "name": "Profesor de Francés" },
    { "name": "Profesor de Español" },
    { "name": "Mecánico Automotriz" },
    { "name": "Mecánico de Bicicletas" },
    { "name": "Electricista" },
    { "name": "Fontanero" },
    { "name": "Carpintero" },
    { "name": "Desarrollador Web" },
    { "name": "Desarrollador de Software" },
    { "name": "Diseñador Gráfico" },
    { "name": "Fotógrafo" },
    { "name": "Editor de Fotos" },
    { "name": "Productor de Música" },
    { "name": "DJ" },
    { "name": "Chef" },
    { "name": "Panadero" },
    { "name": "Pastelero" },
    { "name": "Barista" },
    { "name": "Bartender" },
    { "name": "Nutricionista" },
    { "name": "Entrenador Personal" },
    { "name": "Instructor de Yoga" },
    { "name": "Instructor de Pilates" },
    { "name": "Consultor de Negocios" },
    { "name": "Asesor Financiero" },
    { "name": "Contador Público" },
    { "name": "Abogado" },
    { "name": "Médico General" },
    { "name": "Enfermero" },
    { "name": "Fisioterapeuta" },
    { "name": "Veterinario" },
    { "name": "Ingeniero Civil" },
    { "name": "Ingeniero Eléctrico" },
    { "name": "Ingeniero Mecánico" },
    { "name": "Analista de Datos" },
    { "name": "Científico de Datos" },
    { "name": "Especialista en Ciberseguridad" },
    { "name": "Redactor de Contenidos" },
    { "name": "Copywriter" },
    { "name": "Traductor" },
    { "name": "Intérprete" },
    { "name": "Coach de Vida" },
    { "name": "Coach de Carreras" },
    { "name": "Terapeuta" },
    { "name": "Psicólogo" },
    { "name": "Ilustrador" },
    { "name": "Animador 3D" },
    { "name": "Diseñador de Moda" },
    { "name": "Maquillador" },
    { "name": "Estilista de Cabello" },
    { "name": "Instructor de Baile" },
    { "name": "Actor" },
    { "name": "Director de Cine" },
    { "name": "Guionista" },
    { "name": "Arquitecto" },
    { "name": "Agricultor Orgánico" },
    { "name": "Apicultor" },
    { "name": "Consultor de Energías Renovables" },
    { "name": "Piloto de Avión" },
    { "name": "Controlador Aéreo" },
    { "name": "Navegante" },
    { "name": "Marinero" },
    { "name": "Ingeniero Naval" },
    { "name": "Jardinero" },
    { "name": "Paisajista" },
    { "name": "Editor de Video" },
    { "name": "Gestor de Proyectos" },
    { "name": "Especialista en Marketing Digital" },
    { "name": "Community Manager" },
    { "name": "Especialista en SEO" }
  ]