module.exports = [
  //   {
  //     name: "Nicolas",
  //     last_name: "Morales Romero",
  //     image: "/images/Hombre.jpg",
  //     birthdate: "21/04/2021",
  //     description: "soy el mejor del Front",
  //     password: "Admin@123",
  //     email: "nicomorales@gmail.com",
  //     tel: "2244446245",
  //     Instagram: "",
  //     sexo: "MASCULINO",
  //     professionId: "20",
  //   },
  //   {
  //     name: "Jose",
  //     last_name: "Sat",
  //     image: "/images/Hombre.jpg",
  //     birthdate: "21/04/2021",
  //     description: "soy el mejor QA",
  //     password: "Admin@123",
  //     email: "josesat@gmail.com",
  //     tel: "2244446245",
  //     Instagram: "",
  //     sexo: "MASCULINO",
  //     professionId: "18",
  //   },
  //   {
  //     name: "cristofer",
  //     last_name: "crego",
  //     image: "/images/Hombre.jpg",
  //     birthdate: "21/04/2021",
  //     description: "soy el mejor del back",
  //     password: "Admin@123",
  //     email: "kiki@gmail.com",
  //     tel: "2244446245",
  //     Instagram: "",
  //     sexo: "MASCULINO",
  //     professionId: "14",
  //   },
  //   {
  //     name: "maria",
  //     last_name: "pereira",
  //     image: "/images/Mujer.jpg",
  //     birthdate: "21/04/2021",
  //     description: "soy la mejor del front",
  //     password: "Admin@123",
  //     email: "mariapereira@gmail.com",
  //     tel: "2244446245",
  //     Instagram: "",
  //     sexo: "FEMENINO",
  //     professionId: "15",
  //   },
  //   {
  //     name: "malinda",
  //     last_name: "perez",
  //     image: "/images/Mujer.jpg",
  //     birthdate: "21/04/2021",
  //     description: "soy la mejor QA",
  //     password: "Admin@123",
  //     email: "malindaperez@gmail.com",
  //     tel: "2244446245",
  //     Instagram: "",
  //     sexo: "FEMENINO",
  //     professionId: "11",
  //   },
  //   {
  //     name: "lautaro",
  //     last_name: "miceli",
  //     image: "/images/Hombre.jpg",
  //     birthdate: "21/04/2021",
  //     description: "soy el mejor del front",
  //     password: "Admin@123",
  //     email: "laumiceli@gmail.com",
  //     tel: "2244446245",
  //     Instagram: "",
  //     sexo: "MASCULINO",
  //     professionId: "10",
  //   },
  //   {
  //     name: "franco",
  //     last_name: "huayller",
  //     image: "/images/Hombre.jpg",
  //     birthdate: "21/04/2021",
  //     description: "soy el mejor del back",
  //     password: "Admin@123",
  //     email: "franhuayller@gmail.com",
  //     tel: "2244446245",
  //     Instagram: "",
  //     sexo: "MASCULINO",
  //     professionId: "10",
  //   },
  // ];

  {
    name: "Nicolas",
    last_name: "Morales Romero",
    image: "https://c.superprof.com/i/m/522899/300/20220920110015/522899.webp",
    birthdate: "21/04/2021",
    description:
      "Soy el mejor desarrollador Frontend, apasionado por crear interfaces intuitivas y funcionales con las mejores prácticas de desarrollo web.",
    password: "Admin@123",
    email: "nicomorales@gmail.com",
    tel: "2244446245",
    Instagram: "@Nicolas",
    sexo: "MASCULINO",
    professionId: "13",
  },
  {
    name: "jose",
    last_name: "Sat",
    image: "https://c.superprof.com/i/m/653090/300/20240131130912/653090.webp",
    birthdate: "21/04/2021",
    description:
      "soy el mejor QA con un enfoque en la excelencia y el aseguramiento de la calidad, buscando siempre mejorar los procesos de pruebas.",
    password: "Admin@123",
    email: "josesat@gmail.com",
    tel: "2244446245",
    Instagram: "@Jose",
    sexo: "MASCULINO",
    professionId: "14",
  },
  {
    name: "Cristofer",
    last_name: "Crego",
    image:
      "https://c.superprof.com/i/m/14852853/300/20231022010310/14852853.webp",
    birthdate: "21/04/2021",
    description:
      "Soy el mejor desarrollador Backend, experto en la creación de sistemas robustos y escalables con un enfoque en la eficiencia y seguridad.",
    password: "Admin@123",
    email: "kiki@gmail.com",
    tel: "2244446245",
    Instagram: "@Cristofer",
    sexo: "MASCULINO",
    professionId: "14",
  },
  {
    name: "Maria",
    last_name: "Pereira",
    image:
      "https://c.superprof.com/i/m/1640336/600/20230614170931/1640336.webp",
    birthdate: "21/04/2021",
    description:
      "Soy la mejor desarrolladora Frontend, especializada en la creación de experiencias de usuario atractivas y funcionales, enfocada en el detalle y el rendimiento.",
    password: "Admin@123",
    email: "mariapereira@gmail.com",
    tel: "2244446245",
    Instagram: "@Maria",
    sexo: "FEMENINO",
    professionId: "13",
  },
  {
    name: "Malinda",
    last_name: "Perez",
    image:
      "https://c.superprof.com/i/m/27384577/600/20240331225916/27384577.webp",
    birthdate: "21/04/2021",
    description:
      "Soy la mejor QA, comprometida con la calidad de los productos de software, asegurando la entrega de soluciones que superen las expectativas.",
    password: "Admin@123",
    email: "malindaperez@gmail.com",
    tel: "2244446245",
    Instagram: "@Malinda",
    sexo: "FEMENINO",
    professionId: "40",
  },
  {
    name: "Lautaro",
    last_name: "Miceli",
    image:
      "https://c.superprof.com/i/m/10856203/600/20240401150959/10856203.webp",
    birthdate: "21/04/2021",
    description:
      "Soy el mejor desarrollador Frontend, enfocado en la creación de interfaces innovadoras y accesibles, con atención a la estética y la usabilidad.",
    password: "Admin@123",
    email: "laumiceli@gmail.com",
    tel: "2244446245",
    Instagram: "@Lautaro",
    sexo: "MASCULINO",
    professionId: "13",
  },
  {
    name: "Franco",
    last_name: "Huayller",
    image: "https://c.superprof.com/i/m/22200375/600/20240131050444/22200375.webp",
    birthdate: "21/04/2021",
    description:
      "Soy el mejor desarrollador Backend, apasionado por la arquitectura de software y el desarrollo de soluciones escalables y eficientes.",
    password: "Admin@123",
    email: "franhuayller@gmail.com",
    tel: "2244446245",
    Instagram: "@Franco",
    sexo: "MASCULINO",
    professionId: "10",
  },
];
